### ISSUE TITLE
incompatible Crossplane version: package is not compatible with Crossplane version (v1.16.0-rc.0.38.gdd131a7a)

### ISSUE THREAD

**Issue by machecazzon** [crossplane-contrib/function-environment-configs#19]
### What happened?

```
     Message:               incompatible Crossplane version: package is not compatible with Crossplane version (v1.16.0-rc.0.38.gdd131a7a)
```

> Warning

> **This function relies on functionalities only available in Crossplane 1.15 and later**. It will not work with earlier versions.

### What environment did it happen in?
Function version:  xpkg.upbound.io/crossplane-contrib/function-environment-configs
v0.0.4
v0.0.5

**Comment by machecazzon** [comment]
This works with 1.15.0 thought (tested with v0.0.5)

**Comment by phisco** [comment]
looks like this is a Crossplane issue, the underlying library doesn't handle prereleases as I would have expected: https://github.com/Masterminds/semver/blob/10ab64a0cd83ee20d259b6c0ecdfd785733ea2ee/constraints.go#L411-L416 🤔 you'll have to set `ignoreCrossplaneConstraints: true` when deploying the Function.
